# Generated by Django 4.2.3 on 2025-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempted_questions',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
