# Generated by Django 4.2.3 on 2025-12-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_generatedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField()),
                ('normalized_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], default='ai', max_length=10)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.subcategory')),
            ],
        ),
        migrations.DeleteModel(
            name='GeneratedQuestion',
        ),
    ]
