# Generated by Django 4.2.3 on 2025-12-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
