# Generated by Django 4.2.3 on 2025-12-26 10:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizattempt_paused_at_quizattempt_time_spent_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
