# Generated by Django 5.2.8 on 2025-12-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizattempt_paused_at_quizattempt_time_spent_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='remaining_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
