# Generated by Django 4.2.3 on 2025-12-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_add_time_spent_seconds'),
        ('quizzes', '0008_quizattempt_remaining_seconds'),
    ]

    operations = [
    ]
