# Generated by Django 4.2.3 on 2025-12-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_merge_20251227_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Generating Questions'), (1, 'In Progress'), (2, 'Paused'), (3, 'Completed'), (4, 'Abandoned')], default=0),
        ),
    ]
