# Generated by Django 4.2.3 on 2025-12-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_quizattempt_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Generating Questions'), (1, 'In Progress'), (2, 'Completed'), (3, 'Abandoned')], default=0),
        ),
    ]
